### ISSUE TITLE
Support for atleast OpenGL 4.0

### ISSUE THREAD

**Issue by SuicSoft** [NovaMods/nova-renderer#16]
Nova should support atleast OpenGL 4.0 since only very few GPUs support 4.5 (mine does but only on Windows 10) . Maybe there will be some features that will have to be removed or back ported for OpenGL 4.0

**Comment by dotModded** [comment]
This will most likely not happen, we use features from 4.5.

**Comment by SuicSoft** [comment]
@dotModded What is an example of a feature we use. Maybe I could get it working on older versions (maybe at the cost of performance)

**Comment by DethRaid** [comment]
A couple things:

- openGL 4.5 is at least 4.0. I think you meant to say "support openGL 4.0"  
- what gpu do you have that 4.5 is only supported on Windows 10? One of the nice things about openGL is that it's completely independent from the Windows version, unlike DirectX. 
- we use (or will use when I finally write it) glMultiDrawElementsIndirect, which is core in openGL 4.3 (although it may be available as an extension in earlier openGL versions). There's also some stuff like the direct state access apis and some awesome shader stuff that's only available (as far as I know) in 4.5 and 4.4.  

There's another consideration. I want nova to work with existing shaderpacks. Existing shaderpacks are typically written in glsl 120, but openGL 4.5 uses glsl 450, so one as going to write a 120 to 450 transpiler. Supporting other openGL versions means of have to support more transpilers, which is not something I really want to do.

It's possible that sometime down the road I'll refactor nova to work with older openGL versions and just use extensions for the stuff it needs, but that's not very likely.

Sorry

**Comment by PaintNinja** [comment]
A note on OpenGL 4.5 support... I did a quick search and found that support for OpenGL 4.4 and 4.5 through drivers are fairly common on GPUs within the last 5-7 years. 

OpenGL 4.5 support when using the latest drivers:
- AMD's Radeon HD 7000 series and newer
- NVidia's GeForce 400 series and newer
- Intel HD Graphics in Intel's Broadwell processors and newer

While I am aware that software-added support isn't as performant as native hardware support, it should still work nonetheless. Native hardware support for OpenGL 4.4 has been around since NVidia's GeForce 600 series and AMD's Rx 200 series I think, so it should work fairly well across the board, especially in a couple of years time.

**Comment by SuicSoft** [comment]
@DethRaid @PaintNinja I mean that Linux only is supporting OpenGL 4.1 even with latest Mesa Git. On Ubuntu 14.04 with fglrx it supported OpenGL 4.3 but had a compute shader bug (see supertuxkart/stk-code#2595 , Windows 10 has no problems).I only have tried Windows 10 , not any other versions of Windows.

My GPU is AMD Radeon 7640G. I get 60 FPS on vanilla Minecraft 1.11 with Optifine (playing on both local and servers with lots of buildings) and 25 - 40 FPS on SuperTuxKart at medium - high settings (quite a intensive open source game). I am using the Padoka PPA on Ubuntu 16.04 (actually elementary OS Loki) and AMD website drivers on Windows 10

**Comment by DethRaid** [comment]
Closing as "Not an issue"
