### ISSUE TITLE
I can't compile Nova

### ISSUE THREAD

**Issue by motangish** [NovaMods/nova-renderer#17]
Exception in thread "Client thread" java.lang.UnsatisfiedLinkError: Unable to load library 'nova-renderer'

**Comment by DethRaid** [comment]
Check your jars/natives/1.10/1.10-natives folder. Do you see both libnova-renderer.dll and libstdc++6.dll? (the libstdc++ might not be named exactly that)

**Comment by motangish** [comment]
I don't see libnova-renderer.dll

**Comment by DethRaid** [comment]
Did you run "./nova.ps1 -compile"? Were there any errors with that command?

**Comment by motangish** [comment]
I don't run "./nova.ps1 -compile"

**Comment by DethRaid** [comment]
Well, do that then.

I wrote a page on the wiki with instructions on how to run nova. Follow those instructions.

I think I forgot to write that you have to install the vulkan sdk in order to compile glfw, and nova uses glfw, so you'll have to install the vulkan sdk. Imma look into removing that dependency eventually

**Comment by motangish** [comment]
I ins
